databases:
  - name: poesy
    databaseName: poesy
    user: poesy_admin

services:
  - type: web
    name: poesy
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn poesy.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: poesy
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4