# Generated by Django 3.0.2 on 2020-02-29 22:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=30)),
                ('bio', models.TextField(blank=True, max_length=160)),
                ('image', models.URLField(blank=True, null=True)),
                ('bookmarks', models.ManyToManyField(blank=True, related_name='bookmarked_by', to='poems.Poem')),
                ('follows', models.ManyToManyField(blank=True, related_name='followed_by', to='userprofile.Profile')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_by', to='poems.Poem')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
