# Generated by Django 3.0.2 on 2020-02-29 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poems', '0001_initial'),
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='userprofile.Profile'),
        ),
        migrations.AddField(
            model_name='poem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poems.Topic'),
        ),
    ]
