# Generated by Django 3.0.2 on 2020-03-02 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poems', '0002_auto_20200229_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='poems.Topic'),
        ),
    ]
